// Generated by gencpp from file multiply_two_floats_server_py/MultiplyTwoFloatsRequest.msg
// DO NOT EDIT!


#ifndef MULTIPLY_TWO_FLOATS_SERVER_PY_MESSAGE_MULTIPLYTWOFLOATSREQUEST_H
#define MULTIPLY_TWO_FLOATS_SERVER_PY_MESSAGE_MULTIPLYTWOFLOATSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiply_two_floats_server_py
{
template <class ContainerAllocator>
struct MultiplyTwoFloatsRequest_
{
  typedef MultiplyTwoFloatsRequest_<ContainerAllocator> Type;

  MultiplyTwoFloatsRequest_()
    : a(0.0)
    , b(0.0)  {
    }
  MultiplyTwoFloatsRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyTwoFloatsRequest_

typedef ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<std::allocator<void> > MultiplyTwoFloatsRequest;

typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest > MultiplyTwoFloatsRequestPtr;
typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest const> MultiplyTwoFloatsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator1> & lhs, const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator1> & lhs, const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiply_two_floats_server_py

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f4f9f1b571de73ae8592a1438fd23f3";
  }

  static const char* value(const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f4f9f1b571de73aULL;
  static const uint64_t static_value2 = 0xe8592a1438fd23f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiply_two_floats_server_py/MultiplyTwoFloatsRequest";
  }

  static const char* value(const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n"
"float64 b\n"
;
  }

  static const char* value(const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyTwoFloatsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiply_two_floats_server_py::MultiplyTwoFloatsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLY_TWO_FLOATS_SERVER_PY_MESSAGE_MULTIPLYTWOFLOATSREQUEST_H
