// Generated by gencpp from file multiply_two_floats_server_py/MultiplyTwoFloatsResponse.msg
// DO NOT EDIT!


#ifndef MULTIPLY_TWO_FLOATS_SERVER_PY_MESSAGE_MULTIPLYTWOFLOATSRESPONSE_H
#define MULTIPLY_TWO_FLOATS_SERVER_PY_MESSAGE_MULTIPLYTWOFLOATSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiply_two_floats_server_py
{
template <class ContainerAllocator>
struct MultiplyTwoFloatsResponse_
{
  typedef MultiplyTwoFloatsResponse_<ContainerAllocator> Type;

  MultiplyTwoFloatsResponse_()
    : sum(0.0)  {
    }
  MultiplyTwoFloatsResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef double _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyTwoFloatsResponse_

typedef ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<std::allocator<void> > MultiplyTwoFloatsResponse;

typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse > MultiplyTwoFloatsResponsePtr;
typedef boost::shared_ptr< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse const> MultiplyTwoFloatsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator1> & lhs, const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator1> & lhs, const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiply_two_floats_server_py

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "981739b4699a7cf1b15030371beffb96";
  }

  static const char* value(const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x981739b4699a7cf1ULL;
  static const uint64_t static_value2 = 0xb15030371beffb96ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiply_two_floats_server_py/MultiplyTwoFloatsResponse";
  }

  static const char* value(const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 sum\n"
"\n"
;
  }

  static const char* value(const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyTwoFloatsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiply_two_floats_server_py::MultiplyTwoFloatsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<double>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPLY_TWO_FLOATS_SERVER_PY_MESSAGE_MULTIPLYTWOFLOATSRESPONSE_H
